### ISSUE TITLE
As an admin how do I know who all the Children and Santas are

### ISSUE THREAD

**Issue by gautamMoEngage** [jolicode/slack-secret-santa#6]

**Comment by pyrech** [comment]
Hi :)

At the moment, there is no way to know a posteriori the list of participants and their targets because we do not persist anything on disk (mainly to respect privacy and to keep things simple).

However, it could be possible - during the process - to send a private message to the "admin" to summarize the secret santa. PR are really welcome if you want to give it a try :wink:
